kind: Service
apiVersion: v1
metadata:
  name: creativedrive-api
spec:
  selector:
    app: creativedrive-api
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30081
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: creativedrive-api
spec:
  selector:
      matchLabels:
        app: creativedrive-api
  replicas: 1
  template:
    metadata:
      labels:
        app: creativedrive-api
    spec:
      containers:
        - name: creativedrive-api
          image: tirula/creativedrive-api:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 8080
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: MONGO_URL
              value: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo-service:27017/autenticacao?authSource=admin